//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleDataSource
{
	using System; 
	using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleDataSource { }
#else

	public class SampleDataSource : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleDataSource()
		{
			try
			{
				Uri resourceUri = new Uri("/Test;component/SampleData/SampleDataSource/SampleDataSource.xaml", UriKind.RelativeOrAbsolute);
				System.Windows.Application.LoadComponent(this, resourceUri);
			}
			catch
			{
			}
		}

		private Faq _Faq = new Faq();

		public Faq Faq
		{
			get
			{
				return this._Faq;
			}
		}
	}

	public class FaqItem : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Question = string.Empty;

		public string Question
		{
			get
			{
				return this._Question;
			}

			set
			{
				if (this._Question != value)
				{
					this._Question = value;
					this.OnPropertyChanged("Question");
				}
			}
		}

		private string _Answer = string.Empty;

		public string Answer
		{
			get
			{
				return this._Answer;
			}

			set
			{
				if (this._Answer != value)
				{
					this._Answer = value;
					this.OnPropertyChanged("Answer");
				}
			}
		}
	}

	public class Faq : System.Collections.ObjectModel.ObservableCollection<FaqItem>
	{ 
	}
#endif
}
